### ISSUE TITLE
3rd level projects

### ISSUE THREAD

**Issue by AnythingOverIP** [reubenmallaby/redmine_projects_accordion#10]
It seems that 3rd level objects in the Project list are hidden in a small box... Content is showed there, but it's dissimulated in a box where "standard" users would not look. Is there a way to make either the box bigger or have it showed as other levels?

**Comment by AbstractionFaction** [comment]
I think that was the issue I had with trying to use this.  I forked it and I _think_ that was the one issue I fixed, for what it's worth: https://github.com/adamhouston71/redmine_projects_accordion

**Comment by AnythingOverIP** [comment]
Sorry for not replying sooner! This is indeed the fix I was looking for. @reubenmallaby ,can I suggest to have the mentioned fix be merged ? Cheers!

**Comment by TyRoden** [comment]
I have an odd issue where if a user only has access to 3rd level projects, that they do not show on projects. Jump to a project on the upper right still shows them, but the projects are otherwise totally missing from the page source too. Otherwise.. love what it does for 1st and 2nd level projects.  This issue is with using the fork above by the way.
